name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias Ã  meia-noite
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: Gerar animaÃ§Ã£o da cobrinha ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: kety-tech
          outputs: dist/snake/github-contribution-grid-snake.svg

      - name: Publicar no branch output-snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-snake
          build_dir: dist/snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
